### ISSUE TITLE
ลองทำดู

### ISSUE THREAD

**Issue by Nitikornns** [ford19982541/ford19982541.github.io#3]

**Comment by ford19982541** [comment]
จริงปะจ่ะ

**Comment by Nitikornns** [comment]
จริงจ่ะ

**Comment by Nitikornns** [comment]
![image](https://user-images.githubusercontent.com/36132908/38123930-6882c128-3408-11e8-8a12-0e41d541c6b0.png)

สีนี้ได้มะ พื้นหลังๆ
